# Configuración COMPLETA para Railway
# Deploy de React + PHP + MySQL

[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/test_connection.php"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production]
variables = [
  "NODE_ENV=production",
  "PHP_VERSION=8.1",
  "AFIP_CUIT=20944515411",
  "AFIP_ENVIRONMENT=PRODUCCION", 
  "AFIP_POINT_OF_SALE=3"
]
